STDP synapse and IAF neuron generation for the compartmental feature [WIP]
nest/nestml pull request #1103
Opened 2024-09-24 20:30 UTC by LeanderEwert

Making the creation of NESTML synapses compatible with the compartmental feature requires adjustments, as the compartmental neuron generation pipeline constructs neurons in a fundamentally different way. Since NESTML synapses are paired with their post-synaptic neuron during generation, the STDP feature must be specifically implemented for the compartmental pipeline.

The lack of cross-compartment or global variable access has made it difficult, or at least unintuitive, to write IAF neurons.

The solutions to both problems have significant overlap, which is why both will be addressed in this pull request.

2024-12-03 08:50 UTC, WillemWybo commented
I believe the [executing](https://pypi.org/project/executing/) package should be added to the dependencies.

2025-06-30 10:28 UTC, clinssen requested changes

2025-06-30 10:28 UTC, clinssen commented on doc/running/running_nest_compartmental.rst
> +One variable in the model represents the local membrane potential in a compartment. By default, it is called ``v_comp``. (This name is defined in the compartmental code generator options as the ``com
```suggestion
One variable in the model represents the local membrane potential in a compartment. By default, it is called ``v_comp``. (This name is defined in the compartmental code generator options as the ``compartmental_variable_name`` option.) This variable needs to be defined as a state in any compartmental model to be referenced in the equations describing channels and receptors.
```

2025-06-30 10:28 UTC, clinssen commented on doc/running/running_nest_compartmental.rst
> +Above examples of explicit interdependence inbetween concentration and channel models where already described. Note that it is not necessary to describe the basic interaction inherent through the con
```suggestion
Above examples of explicit interdependence inbetween concentration and channel models were already described. Note that it is not necessary to describe the basic interaction inherent through the contribution to the overall current of the compartment. During a simulation step all currents of channels and receptors are added up and contribute to the change of the membrane potential (v_comp) in the next timestep. Thereby one must only express a dependence explicitly if the mechanism depends on the activity of a specific channel- or receptor-type amongst multiple in a given compartment or some concentration.
```

2025-06-30 10:28 UTC, clinssen commented on doc/running/running_nest_compartmental.rst
> +Even though the intended focus of the compartmental feature is the usage of the above mechanisms whose influence on the compartment and overall neurons is implicit, it is still possible to use the up
```suggestion
Even though the intended focus of the compartmental feature is the usage of the above mechanisms whose influence on the compartment and overall neurons is implicit, it is still possible to use the ``update`` block. The ``update`` block does not control the overall behaviour of the neuron but its computation may support the behaviour of mechanisms within a compartment. All states occuring inside of the ``update`` block or within the called functions and inlines etc. become part of a general computation block that is always executed once for each compartment. These states may be used by the mechanisms. The ODEs owned by the update block are still integrated automatically and ``integrate_odes()`` shall not be used in this context.
```

2025-06-30 10:28 UTC, clinssen commented on doc/running/running_nest_compartmental.rst
> +Update block:
```suggestion
Update block
```

2025-06-30 10:28 UTC, clinssen commented on doc/running/running_nest_compartmental.rst
> +OnReceive(self_spikes):
```suggestion
onReceive(self_spikes)
```

2025-06-30 10:28 UTC, clinssen commented on doc/running/running_nest_compartmental.rst
> +We also introduce a new special case of the OnReceive block with the CM feature specific variable self_spikes which is just a boolean that is true if and only if the neuron has spiked in the last tim
```suggestion
We also introduce a new special case of the ``onReceive`` block with the compartmental feature-specific variable ``self_spikes``, which is just a boolean that is true if and only if the neuron has spiked in the last timestep. The code within this block is only executed if the neuron spikes (somatic). Otherwise, the same rules as for the ``update`` block apply.
```

2025-06-30 10:28 UTC, clinssen commented on doc/running/running_nest_compartmental.rst
> +Application:
```suggestion
Application
```

2025-06-30 10:28 UTC, clinssen commented on pynestml/cocos/co_co_v_comp_exists.py
> +import traceback
necessary? otherwise remove

2025-06-30 10:28 UTC, clinssen commented on pynestml/cocos/co_cos_manager.py
> +            if not syn_model:
can this instead be done using ``isinstance(model, ASTSynapse)``?

2025-06-30 10:28 UTC, clinssen commented on pynestml/codegeneration/nest_compartmental_code_generator.py
> +        "delay_variable": {},
Could you also update the docstring for the class to include these options? You can just copy them from the NEST code generator.

2025-06-30 10:28 UTC, clinssen commented on pynestml/codegeneration/printers/cpp_function_call_printer.py
> +        if function_name == PredefinedFunctions.HEAVISIDE:
Please also add documentation for the Heaviside function in ``predefined_functions.py`` as well as the NESTML rST docs in the ``docs`` folder. Also complete the register_... methods in ``predefined_functions.py``.

2025-06-30 10:28 UTC, clinssen commented on pynestml/codegeneration/printers/cpp_function_call_printer.py
> +        if function_name == 'Min':
duplicate, remove

2025-06-30 10:28 UTC, clinssen commented on pynestml/codegeneration/resources_nest_compartmental/cm_neuron/@NEURON_NAME@.cpp.jinja2
> +{#
please remove the commented-out template section

2025-06-30 10:28 UTC, clinssen commented on pynestml/codegeneration/resources_nest_compartmental/cm_neuron/cm_global_dynamics.cpp.jinja2
> +{% endwith %}
newline at end of file

2025-06-30 10:28 UTC, clinssen commented on pynestml/codegeneration/resources_nest_compartmental/cm_neuron/cm_global_dynamics.h.jinja2
> +{% endwith -%}
newline at end of file

2025-06-30 10:28 UTC, clinssen commented on pynestml/codegeneration/resources_nest_compartmental/cm_neuron/cm_global_dynamics.h.jinja2
> +///////////////////////////////////// global
should there be an ``#ifdef CM_GLOBAL_DYNAMICS_H``? Could you improve/remove the comment?

2025-06-30 10:28 UTC, clinssen commented on pynestml/codegeneration/resources_nest_compartmental/cm_neuron/cm_neuroncurrents_@NEURON_NAME@.h.jinja2
> +{%- with %}
needed? remove

2025-06-30 10:28 UTC, clinssen commented on pynestml/codegeneration/resources_nest_compartmental/cm_neuron/cm_neuroncurrents_@NEURON_NAME@.h.jinja2
> +    if(!initialized){
why is this necessary?

2025-06-30 10:28 UTC, clinssen commented on pynestml/codegeneration/resources_nest_compartmental/cm_neuron/cm_neuroncurrents_@NEURON_NAME@.h.jinja2
> +    {%- with %}
necessary?

2025-06-30 10:28 UTC, clinssen commented on pynestml/codegeneration/resources_nest_compartmental/cm_neuron/cm_neuroncurrents_@NEURON_NAME@.h.jinja2
>    {%- with %}
necessary?

2025-06-30 10:28 UTC, clinssen commented on pynestml/codegeneration/resources_nest_compartmental/cm_neuron/setup/common/ModuleClassMaster.jinja2
>  }
newline at end of file

2025-06-30 10:28 UTC, clinssen commented on pynestml/utils/ast_global_information_collector.py
> +                                    # if not (isinstance(global_info["root_expression"],
remove commented code

2025-06-30 10:28 UTC, clinssen commented on pynestml/utils/ast_global_information_collector.py
> +                # IMPLEMENT CATCH NONDEFINED!!!
?

2025-06-30 10:28 UTC, clinssen commented on pynestml/utils/ast_global_information_collector.py
> +        # global_info["Dependencies"] = mechanism_dependencies
remove

2025-06-30 10:28 UTC, clinssen commented on pynestml/utils/ast_mechanism_information_collector.py
> +import copy
please group/alphabetise imports

2025-06-30 10:28 UTC, clinssen commented on pynestml/utils/ast_mechanism_information_collector.py
> +                    if not (variable.name == "v_comp" or variable.name in PredefinedUnits.get_units()):
this is a bit risky as there can be variables defined with names of physical units (e.g. "a"). Better to see if the name can be resolved to a variable; if not, check if it can be resolved to a type. See ``ast_variable_visitor.py``.

2025-06-30 10:28 UTC, clinssen commented on pynestml/utils/ast_receptor_information_collector.py
> +from _collections import defaultdict
why the underscore?

2025-06-30 10:28 UTC, clinssen commented on pynestml/utils/global_info_enricher.py
> +    def __init__(self):
empty __init__() can be removed

2025-06-30 10:28 UTC, clinssen commented on pynestml/utils/global_processing.py
> +    """Manages the collection of basic information necesary for all types of mechanisms and uses the
To all new files in the utils directory: could you add a note to the docstrings saying that these are for the compartmental code generator?

2025-06-30 10:28 UTC, clinssen commented on pynestml/utils/syns_info_enricher.py
> +    def __init__(self):
can be removed

2025-06-30 10:28 UTC, clinssen commented on tests/nest_compartmental_tests/resources/cm_iaf_psc_exp_dend_neuron.nestml
> +        refr_t = refr_T
newline at end of file

2025-06-30 10:28 UTC, clinssen commented on tests/nest_compartmental_tests/resources/invalid/CoCoCmMechSharedCode.nestml
> +model CoCoCmSharedCode:
Could you include the copyright header in all new .nestml file?

2025-06-30 10:28 UTC, clinssen commented on tests/nest_compartmental_tests/resources/invalid/CoCoCmMechSharedCode.nestml
> +        shared_and_global_state = shared_and_global_state + 1.
newline

2025-06-30 10:28 UTC, clinssen commented on tests/nest_compartmental_tests/resources/update_block_variation_test.nestml
> +# iaf_psc_exp_dend - Leaky integrate-and-fire neuron model with exponential PSCs
update docstring

2025-06-30 10:28 UTC, clinssen commented on tests/nest_compartmental_tests/resources/stdp_synapse.nestml
> +# stdp - Synapse model for spike-timing dependent plasticity
Is it necessary to duplicate these files? Can the ``integrate_odes()`` call not just be ignored in the ``update`` block of the existing .nestml synapse models?

2025-06-30 12:04 UTC, LeanderEwert commented on pynestml/cocos/co_cos_manager.py
> +            if not syn_model:
Everything is just ASTModel, no?

2025-06-30 15:48 UTC, LeanderEwert commented on tests/nest_compartmental_tests/resources/stdp_synapse.nestml
> +# stdp - Synapse model for spike-timing dependent plasticity
In principle, yes, but I think it would be misleading to allow instructions that don't have any effect. On the other hand it would be nice if all standard synapse models would be compatible with the compartmental generation. Not so sure about it.

2025-07-02 18:35 UTC, clinssen commented on tests/nest_compartmental_tests/resources/stdp_synapse.nestml
> +# stdp - Synapse model for spike-timing dependent plasticity
In that case, could you please add a line in the docstring for the model explaining what it is intended for/why the difference?

2025-07-02 19:38 UTC, LeanderEwert commented on tests/nest_compartmental_tests/resources/stdp_synapse.nestml
> +# stdp - Synapse model for spike-timing dependent plasticity
I have added a sentence to the description in the header.

2025-07-03 11:57 UTC, LeanderEwert commented on pynestml/utils/ast_mechanism_information_collector.py
> +                    if not (variable.name == "v_comp" or variable.name in PredefinedUnits.get_units()):
I can't remember the context of why I added this with 100% certainty, but I think it was because my variable collector would collect type declarations as if they were variables. So, something like var1 pA = 1. pA would result in two variables, var1 and pA.

2025-10-28 15:51 UTC, WillemWybo commented
I wonder if this can be merged @clinssen @pnbabu ?

2025-12-23 17:11 UTC, clinssen approved these changes

2026-01-06 10:41 UTC, pnbabu requested changes

2026-01-06 10:41 UTC, pnbabu commented on pynestml/cocos/co_co_cm_global.py
> +        :type neuron: ast_neuron
```suggestion
```

2026-01-06 10:41 UTC, pnbabu commented on pynestml/cocos/co_co_cm_mech_shared_code.py
> +                info["Internals"].keys()))  # + [e.get_name() for e in info["Dependencies"]["global"]]
Please remove the comment.

2026-01-06 10:41 UTC, pnbabu commented on pynestml/cocos/co_co_cm_mech_shared_code.py
> +class CoCoCmMechSharedCode(CoCo):
Could you add docs to this coco?

2026-01-06 10:41 UTC, pnbabu commented on pynestml/codegeneration/printers/cpp_function_call_printer.py
> +        if function_name == PredefinedFunctions.MIN or function_name == "Min":
Why the extra function `Min` here?

2026-01-06 10:41 UTC, pnbabu commented on pynestml/codegeneration/nest_compartmental_code_generator.py
> +        # assert synapse_name_stripped in self.get_option("delay_variable").keys(), "Please specify a delay variable for synapse '" + synapse_name_stripped + "' in the code generator options"
Do you need these assert statements?

2026-01-06 10:41 UTC, pnbabu commented on pynestml/frontend/pynestml_frontend.py
> +    if target_name.upper() in ["NEST"]:
Why this change?

2026-01-06 10:41 UTC, pnbabu commented on pynestml/utils/channel_processing.py
> +    Extends MechanismProcessing. Searches for Variables that if 0 lead to the root expression always beeing zero so
```suggestion
    Extends MechanismProcessing. Searches for Variables that if 0 lead to the root expression always being zero so
```

2026-01-06 10:41 UTC, pnbabu commented on tests/nest_compartmental_tests/resources/cm_iaf_psc_exp_dend_neuron.nestml
> +# iaf_psc_exp_dend - Leaky integrate-and-fire neuron model with exponential PSCs
Could you change the file name here and add a short description specific to the compartment model?

2026-01-06 10:41 UTC, pnbabu commented on tests/nest_compartmental_tests/resources/recordable_inline_test.nestml
> +# recordable inlines test model
Could you add the file name here?

2026-01-06 10:41 UTC, pnbabu commented on tests/nest_compartmental_tests/test__compartmental_model.py
> +        if True:
Remove `if True`.

2026-01-06 10:41 UTC, pnbabu commented on tests/nest_compartmental_tests/test__compartmental_model.py
> +                logging_level="ERROR"
It's better to have at least `INFO` logging level as it's easier to debug in case of CI failures.

2026-01-06 10:41 UTC, pnbabu commented on tests/nest_compartmental_tests/test__self_spike_convolutions.py
> +        """We test the concentration mechanism by comparing the concentration value at a certain critical point in
Could you add an assert to this test?

2026-06-04 16:25 UTC, LeanderEwert commented on pynestml/codegeneration/resources_nest_compartmental/cm_neuron/cm_neuroncurrents_@NEURON_NAME@.h.jinja2
>    {%- with %}
Are you referring to the with endwith stuff?

2026-06-04 16:25 UTC, LeanderEwert commented on pynestml/codegeneration/resources_nest_compartmental/cm_neuron/cm_neuroncurrents_@NEURON_NAME@.h.jinja2
> +    if(!initialized){
This is because the pre_run_hook is called at every call to nest.Simulate, but we would only like this to be done at the first Simulate call..

2026-06-04 16:25 UTC, LeanderEwert commented on pynestml/frontend/pynestml_frontend.py
> +    if target_name.upper() in ["NEST"]:
Hmm, as far as I can see in the history, this was changed back and forth a bunch. Personally, I think this is nice because it is visually more coherent with the other cases, like: 
...
if target_name.upper() in ["NEST", "SPINNAKER"]:
...
But I think this wasn't really a conscious decision, just an auto-merge decission.

2026-06-09 14:59 UTC, clinssen commented on pynestml/cocos/co_cos_manager.py
> +        conflicting_nodes = list()
This cannot be implemented as a separate CoCo class, as it doesn't operate on ASTNodes, but lists of ASTNodes.

2026-06-18 16:36 UTC, clinssen approved these changes
Many thanks for this contribution!

2026-06-18 16:36 UTC, merged