Add syntax highlighting for python in documentation
nest/nestml pull request #579
Opened 2020-09-19 19:15 UTC by Silmathoron

This PR adds correct highlighting for python code blocks.

2020-09-21 08:22 UTC, jougs approved these changes

2020-09-21 08:32 UTC, clinssen commented
I still have an open PR against @Silmathoron's branch, please don't merge just yet!

2020-09-21 08:44 UTC, Silmathoron commented
Ah, sorry, did not see it was a PR on my branch ^^"
Just rebased it

2020-09-21 08:45 UTC, jougs commented
No worries, I just wanted to indicate my approval. Please merge yourself whenever you think it's ready.

2020-09-22 09:52 UTC, clinssen requested changes

2020-09-22 09:52 UTC, clinssen commented on doc/tutorial/izhikevich_tutorial.rst
> +.. code-block:: python
```suggestion
.. code-block:: bash
```
My bad.

2020-09-22 09:52 UTC, merged

2020-09-22 09:52 UTC, clinssen commented
Many thanks!