Issue #533: Fix print, println functions
nest/nestml pull request #600
Opened 2021-01-05 15:17 UTC by pnbabu

Support print and println functions in NESTML

2021-01-06 10:50 UTC, clinssen commented
For println, please set the argument type correctly in line 151 of pynestml/symbols/predefined_functions.py.

I'm still getting some runtime errors when printing more than two variables/parameters, e.g.
```nestml
parameters:
  bar ms = 42 ms
end

update:
  print("bar is: {bar}, bar = {bar}, bar = {bar}")
end
```

Do you think we should also print the physical unit, so it would print "bar is 42 ms" rather than "bar is 42"? This is a little tricky because physical units are known at the NESTML (Python) level, but once we generate C++ code, the parameters and variables are normalised, so we would have to keep track of the multipliers (e.g. all currents are assumed to be in pA in NEST).

2021-01-06 11:32 UTC, pnbabu commented
Thanks for pointing the error case. I had to split the print statement for the first occurrence of the variable instead of all of them. Fixed it in the recent commit.

It would be good to print the values along with the physical unit. I will see how we can accommodate this in the code.

2021-01-15 14:38 UTC, pnbabu commented
The pending task is to add integration tests for nest with print statements having variables with nest-incompatible units and to check if the unit conversion happens and the right units are displayed in the cout statements.

2021-01-18 22:26 UTC, clinssen reviewed
I think the SI standard is to have one space between the number and the unit, could you double-check this and maybe even add a reference to the API docstrings?

I ran into a bug with the units, I'm not sure it's related but if you could please apply this diff:

```
--- a/pynestml/codegeneration/nest_reference_converter.py
+++ b/pynestml/codegeneration/nest_reference_converter.py
@@ -245,7 +245,7 @@ class NESTReferenceConverter(IReferenceConverter):
         variable_name = NestNamesConverter.convert_to_cpp_name(variable.get_complete_name())
         symbol = variable.get_scope().resolve_to_symbol(variable_name, SymbolKind.VARIABLE)
         if isinstance(symbol.get_type_symbol(), UnitTypeSymbol):
-            return symbol.get_type_symbol().unit.unit.name
+            return symbol.get_type_symbol().unit.unit.to_string()
 
         return ''
```

2021-01-18 22:53 UTC, jougs commented
> I think the SI standard is to have one space between the number and the unit, could you double-check this and maybe even add a reference to the API docstrings?

I am not aware we ever formally discussed this previously for NEST. However, as @clinssen correctly points out, the SI standard is to have a space between the numerical value and unit symbol (see [#15 here](https://physics.nist.gov/cuu/Units/checklist.html)) and `rgrep "\" ms" *` produces hits, which means that we're already following that recommendation at least to a certain degree.

@sarakonradi, could you please write this policy down in the appropriate documentation guideline?

2021-01-19 10:35 UTC, pnbabu commented
> I think the SI standard is to have one space between the number and the unit, could you double-check this and maybe even add a reference to the API docstrings?
> 
> I ran into a bug with the units, I'm not sure it's related but if you could please apply this diff:
> 
> ```
> --- a/pynestml/codegeneration/nest_reference_converter.py
> +++ b/pynestml/codegeneration/nest_reference_converter.py
> @@ -245,7 +245,7 @@ class NESTReferenceConverter(IReferenceConverter):
>          variable_name = NestNamesConverter.convert_to_cpp_name(variable.get_complete_name())
>          symbol = variable.get_scope().resolve_to_symbol(variable_name, SymbolKind.VARIABLE)
>          if isinstance(symbol.get_type_symbol(), UnitTypeSymbol):
> -            return symbol.get_type_symbol().unit.unit.name
> +            return symbol.get_type_symbol().unit.unit.to_string()
>  
>          return ''
> ```

What is the bug that you ran into?

2021-01-19 11:26 UTC, pnbabu commented
> I think the SI standard is to have one space between the number and the unit, could you double-check this and maybe even add a reference to the API docstrings?
> 

Thanks for pointing this out. I added a space between the variable and the physical unit and also updated the API docstrings.

> I ran into a bug with the units, I'm not sure it's related but if you could please apply this diff:
> 
> ```
> --- a/pynestml/codegeneration/nest_reference_converter.py
> +++ b/pynestml/codegeneration/nest_reference_converter.py
> @@ -245,7 +245,7 @@ class NESTReferenceConverter(IReferenceConverter):
>          variable_name = NestNamesConverter.convert_to_cpp_name(variable.get_complete_name())
>          symbol = variable.get_scope().resolve_to_symbol(variable_name, SymbolKind.VARIABLE)
>          if isinstance(symbol.get_type_symbol(), UnitTypeSymbol):
> -            return symbol.get_type_symbol().unit.unit.name
> +            return symbol.get_type_symbol().unit.unit.to_string()
>  
>          return ''
> ```

I checked that the variable `name` in `unit` is of type `str`. Could you tell me how this change fixes the bug you are seeing?

2021-01-19 13:11 UTC, clinssen commented
> What is the bug that you ran into?

Try replacing "V" in "V_m V = -50 mV" into "MA*Ohm" to trigger it.

2021-01-19 14:08 UTC, pnbabu commented
> > What is the bug that you ran into?
> 
> Try replacing "V" in "V_m V = -50 mV" into "MA*Ohm" to trigger it.

Yes, you are right. Updated the code and test. Thank you.

2021-01-21 10:14 UTC, clinssen approved these changes
Excellent, thanks a lot!

2021-01-22 22:25 UTC, jougs approved these changes
Very nice! I'm especially impressed by the tests :-)

2021-01-23 22:56 UTC, clinssen commented
One more thing: could you add support for printing the predefined variable t (for time)? Because it is not defined explicitly in any NESTML model, we can assume that its corresponding unit is the "neuroscience unit" of the target platform.

2021-01-29 11:34 UTC, clinssen commented
Perfect, cheers!

Just as a note for future reference: the time variable issue has been spun off to #609.

2021-01-29 11:39 UTC, clinssen requested changes

2021-01-29 11:39 UTC, clinssen commented on pynestml/codegeneration/nest_reference_converter.py
> +.. code-block:: nestml
```suggestion
        .. code-block:: nestml
```

2021-01-29 11:39 UTC, clinssen commented on pynestml/codegeneration/nest_reference_converter.py
> +.. code-block:: nestml
To make sure that this renders nicely as HTML, we have to be really pedantic about the whitespace: the code itself is indented three spaces beyond the start of "..", so e.g.:
```
.. code-block:: nestml
   print("Hello world")
```

Converted NEST:
```
.. code-block:: C++
   std::cout << "Hello world";
```

2021-01-29 11:39 UTC, clinssen commented on tests/nest_tests/print_statement_test.py
> +
Could you add one-line docstring here describing what is tested for?

2021-02-04 13:35 UTC, clinssen approved these changes

2021-02-04 13:35 UTC, merged