GitHub actions for NESTML
nest/nestml pull request #621
Opened 2021-02-16 14:42 UTC by pnbabu

- Migrate content from `.travis.yml` to `.github/workflows/nestml-build.yml`
- Remove `.travis.yml` file
- Successful build link: https://github.com/pnbabu/nestml/actions/runs/571667802

2021-02-16 20:28 UTC, jougs approved these changes
Amazing work! Many thanks! I hereby approve, but leave the final decision to @clinssen.

2021-02-18 10:30 UTC, clinssen requested changes
Many thanks for this! Just a few comments.

The "Install NESTML" stage appears twice in slightly different form, is this necessary?

2021-02-18 10:30 UTC, clinssen commented on .github/workflows/nestml-build.yml
> +      - name: Python dependecies
```suggestion
      - name: Python dependencies
```

2021-02-18 10:30 UTC, clinssen commented on .github/workflows/nestml-build.yml
> +          python -m pip install cython pytest-xdist
```suggestion
          python -m pip install cython
```
I believe this is no longer necessary.

2021-02-18 10:53 UTC, clinssen commented
One more suggestion. Could we use the same versions for Antlr (in Java) as for the Python Antlr4 runtime?  Right now the former is at 4.8 and the latter is at 4.9.1. This results in a lot of warning messages in the log. Either we can ==4.8 in requirements.txt, or you'll have to update the links to the Antlr .jar download. Cheers!

2021-02-18 12:20 UTC, pnbabu commented
> One more suggestion. Could we use the same versions for Antlr (in Java) as for the Python Antlr4 runtime? Right now the former is at 4.8 and the latter is at 4.9.1. This results in a lot of warning messages in the log. Either we can ==4.8 in requirements.txt, or you'll have to update the links to the Antlr .jar download. Cheers!

Yes, changed the version of the jar to 4.9.1

2021-02-21 11:15 UTC, clinssen approved these changes
Don't know why the removed .travis.yml is giving a merge conflict—if you could just fix that, I'm A-OK with the changes. Really great to have this, many thanks!

2021-02-22 09:11 UTC, clinssen approved these changes

2021-02-22 09:12 UTC, merged