cm_syns branch (new compartmental model + synapses) for review
nest/nestml pull request #668
Opened 2021-07-08 12:13 UTC by pythonjam

Hi @clinssen, @pnbabu . 
I submit my current code for review and feedback. Thanks :)

This also contains a newer compartmental model, the old PR request is therefore somewhat stale.

2021-11-19 13:39 UTC, clinssen requested changes
Could you make a NestCompartmentalCodeGenerator that subclasses NestCodeGenerator, so that ideally there are only minimal changes to ``nest_codegenerator.py``?

2021-11-19 13:39 UTC, clinssen commented on pynestml/cocos/co_cos_manager.py
> +        cls.check_compartmental_model(neuron, after_ast_rewrite)
Can we run these only if code generation target is "NEST-compartmental"?

2021-11-19 13:39 UTC, clinssen commented on pynestml/codegeneration/resources_nest/ModuleClass.jinja2
> +    {%- if neuron.is_compartmental_model -%}
Templates to their own directory according to the new scheme (https://github.com/nest/nestml/pull/669).

2021-11-19 13:39 UTC, clinssen commented on pynestml/utils/ast_synapse_information_collector.py
> +"""
Does it make sense from an organisational perspective to have a subdirectory ``pynestml/utils/compartmental`` for these utils files?

2021-11-19 13:39 UTC, clinssen commented on tests/docstring_comment_test.py
> +    # for some reason xfail is completely ignored when executing on my machine (python 3.8.5)
Please remove this from the PR.

2021-12-05 23:09 UTC, pythonjam commented
The new branch that is properly merged is cm_structured

2021-12-05 23:09 UTC, closed without merging