Move custom templates code to the `CodeGenerator` class
nest/nestml pull request #757
Opened 2022-04-12 09:37 UTC by pnbabu

2022-05-11 09:45 UTC, pnbabu commented
> This looks great! Two minor questions: why the removed test, and there are a lot of unrelated formatting changes due to line length; are they causing our CI static check to error out? It should be ignoring line length (E501).

The test was a duplicate, hence removed. My IDE auto-formatted some lines, have undone them now.

2022-05-17 21:50 UTC, clinssen requested changes

2022-05-17 21:50 UTC, clinssen commented on pynestml/utils/with_options.py
> +    r"""This class allows options (indexed by strings) to be set and retrieved. A set of default options may be supplied by overriding the `_default_options` member in the inheriting class. """
undo

2022-05-17 21:50 UTC, clinssen commented on pynestml/utils/with_options.py
> +        r"""Set options. "Eats off" any options that it knows how to set, and returns the rest as "unhandled" options. """
undo

2022-05-18 12:05 UTC, clinssen commented
Many thanks!

2022-05-18 12:05 UTC, merged