Fix convolutions integration and enhance integrate_odes() to integrate specific ODEs
nest/nestml pull request #879
Opened 2023-03-13 21:01 UTC by clinssen

Fixes #440.

2023-04-19 12:06 UTC, clinssen commented
Should be merged after #897. Please wait with your review until this PR is out of draft state. Cheers!

2024-01-05 16:06 UTC, pnbabu requested changes

2024-01-24 16:12 UTC, tomtetzlaff commented on doc/nestml_language/nestml_language_concepts.rst
1) Expressions and operators:List of operators

Replace 

"Multiplication, Division and Modulo-Operator" 

by 

"Multiplication, Division and Modulo operator"

2) Blocks:Block types:internals

Replace 

"variables that supposed to be constant"

by 

"quantities that are supposed to be constant"

3) Blocks:Block types:state

For the neuron models, all variables declared in the state block are automatically "recordable", right? Maybe we should mention this here. How is this for synapse models?

4) Blocks:Block types:onReceive

Here, it would be helpful to explain in more detail how optional weights or priorities can be specified. Maybe via an example. In addition, add a link to "Handling spiking input" where the priorities (but not the weights) are explained.

5) Input:Spiking input ports

Several issues:

i) First, the exact meaning of the input spikes is not clear to me. This little example


```
  input:
    input_spikes  <- spike

  update:
    println("{input_spikes}")	
```

prints out "0 1/s", "0.001 1/s" or "0.002 1/s" at time steps where 0, 1 or 2 spikes arrive, respectively. I convinced myself that these numbers do not dependent on the simulation time resolution $dt$. If `input_spikes` was a time-discrete approximation of (a train of) Dirac delta functions, I would expect something like $n_k/dt$, where $n_k$ is the number of spikes arriving in time step $k$. Alternatively, `input_spikes` could simply be $n_k$. Both interpretations would make sense to me. Currently, however, `input_spikes` seems to be defined as $n_k/1000$/s. What's the rationale behind this?

I'm asking this because, ideally, I would treat input spikes as inhomogeneities in the ODEs, like this:

```
state:
   V mV = 0.0 mV

parameters:
   tau ms = 10 ms

input:
   input_spikes 1/s <- spike

equations:
   V' = -V/tau + input_spikes * mV
```

Currently, however, this gives wrong results. I could fix this by changing the last line to

```
   V' = -V/tau + input_spikes/dt*s * mV
```

I find this suboptimal, because the model definition should not depend on implementation details such as the simulation time resolution $dt$, right?

ii) Second, at the moment, spiking inputs are defined in the NESTML code without unit:

```
input_spikes <- spike
```

Only those users who actually consult the documentation will learn that there is an invisible unit 1/s attached to the spikes. I think it would be more transparent and more consistent to define the input spikes with the unit 1/s, as with all other parameters and variables. Like this:

```
input:
    input_spikes 1/s <- spike
```

iii) Third, in the neuron models, the spiking inputs actually represent the *superposition* of all spikes arriving at a given time point, each of them *weighted* by a synapse-specific coefficient (the synaptic weight). The input spikes to neuron $i$ hence must be interpreted as something like

$$
x_i(t) = \sum_j w_{ij} s_j(t),
$$

where

$$
s_j(t) =  \sum_k \delta(t-t^k_j)
$$

refers to the spike train of presynaptic neuron $j$ and $t^k_j$ to the time of the $k$th spike emitted by neuron $j$. The true unit of the spiking inputs is hence [w]/s, where [w] denotes the units of the weight. In NEST, this unit depends on the type of the postsynaptic neuron (e.g., mV for iaf_psc_delta, or pA for iaf_psc_exp). So we often say that the weight has units pA, mV, etc. But then, on the other hand, in the synapse models, the weights are usually defined as dimensionless quantities:

```
parameters:
    w real = 1.
```

The only way to make things consistent is to treat synaptic weights in NESTML as dimensionless quantities, both in the neuron models and in the synapse models, right? In the neuron models, the final unit is then given by the definition of the synaptic current, something like this:

```
state:
    I_syn pA = 0.0 pA
   
input:
    input_spikes 1/s <- spikes

equations:
    I_syn' = - I_syn/tau_syn + input_spikes * pA
```

This is roughly what we have right now, but it is not clearly documented, is it?

iv) Fourth, in the synapse models, the input spikes are the *non-weighted* spikes $s_j(t)$ of the respective  *individual* presynaptic neuron. In other words, the neuron models and the synapse models require different interpretations of the spiking inputs. This can be very confusing. I think that the documentation should make clear that the `spike`s arriving at the synapse and those arriving at the neuron are different things. 

Here's is a draft for a revised text:

#######################################################

#### Spiking input ports

The dynamics of neurons and synapses are typically driven by incoming spikes. In NESTML, these input spikes are specified via the `spike` input port:

```
input:
   input_spikes 1/s <- spike
```

Neuron models and synapse models require slightly different interpretations of these ports (see [figure below](link:signal_flow_across_neurons_and_synapses.png)): in the synapse models, the incoming spikes represent the spike train 

$$
s_j(t) =  \sum_k \delta(t-t^k_j)
$$

of the respective presynaptic neuron $j$. In the neuron models, in contrast, incoming spikes represent the superposition 

$$
x_i(t) = \sum_l w_{il} s_l(t),
$$

of all presynaptic spike trains arriving at the target neuron $i$, each of them **weighted** by a synaptic weight $w_{il}$. Note that, in NESTML, the weights are always treated as dimensionless quantities. Hence, both $s_j(t)$ and $x_i(t)$ have the same unit 1/s (this follows from the definition of the Dirac delta function). In the neuron models, the weighted input $x_i(t)$ serves as an inhomogeneity of the neuronal dynamics. In the definition of this dynamics, the user has to make sure that the units of the involved state variables are correctly assigned. 

Example:

```
state:
   V mV = 0.0 mV

parameters:
   tau ms = 10 ms

input:
   input_spikes 1/s <- spike

equations:
   V' = -V/tau + input_spikes * mV
```

In this example, the unit `mV` is attached to the dynamics of `V` to ensure consistent dimensions. 

#######################################################

Here's the figure menioned in the above text:

https://fz-juelich.sciebo.de/s/9FpGcPsZZatlJfK

Whether the text proposed above makes sense depends on the answer to my point 5.i above. 

6) Handling spiking input

Replace 

"Spiking input can be handled by convolutions with kernels (see link:Integrating spiking input)"

by

"Spiking input can be handled by directly using them in the `equations` block (see below and link:Integrating spiking input) as inhomogeneities in the dynamical system defining the model dynamics"

I'd recommend not to promote the usage of "convolutions" in the documentation, for the reasons we discussed earlier. 

7) Equations:Systems of ODEs

When trying to compile this code

```
state:
	x real = 0.0 
	x' 1/s = 1.0 /s
	
equations:
	x''= 1.0 /s**2	
```
		
I learn that "higher-order inhomogeneous ODEs are not supported". Maybe this should be mentioned here.

This

```
state:
	 x real = 0.0 
	 x' 1/s = 1.0 /s
	
equations:
	x''= 0.0 /s**2	
```

in contrast, works fine. 

8) Equations:Inline expressions

Replace 

"The `recordable` keyword can be used to make inline available to recording devices:"

by

"The `recordable` keyword can be used to make inline variables available to recording devices:"

9) Equations:Inline expressions

I don't fully understand the paragraph starting with "During simulation...". How about this:

"
Note that inline variables can usually not be used outside the equation block. There is, however, one exception if an inline expression containing the `convolve()` function is marked as recordable, such as

```
recordable inline I_syn pA = convolve(alpha_kernel, spiking_input_port) * pA
```

In this case, the inline variable can be treated like a state variable. It could, for example, be reset in the update block:

```
update:
  # reset the state of synaptic integration
  I_syn = 0 pA
  I_syn' = 0 * s**-1
```
"

10) Equations:Kernel function

Replace
 [...]

2024-02-01 11:47 UTC, tomtetzlaff commented on doc/nestml_language/index.rst
> +NESTML is a domain specific language for the specification of models; typically, the individual neurons and synapses that make up a neural network. NESTML is a completely generic language for hybrid
Possibly leave a note here that NESTML is agnostic of the simulation backend, such as the numerical update schemes, ODE solvers etc.

2024-04-19 12:25 UTC, clinssen commented on doc/running/running_nest.rst
> +
I think it's okay to focus on NEST >3 in our documentation; NEST 2 is "not recommended for new developement".

2024-04-19 12:35 UTC, clinssen commented on doc/nestml_language/nestml_language_concepts.rst
> -Physical unit literals
Redundant with line 107.

2024-04-19 12:44 UTC, clinssen commented on pynestml/codegeneration/resources_nest/point_neuron/common/NeuronClass.jinja2
> +  , spike_input_received_grid_sum_( std::vector< double >( NUM_SPIKE_RECEPTORS ) )
Because we need to trigger an event handler even if a spike was received with weight 0, so we need another "boolean" RingBuffer.

2024-04-19 14:10 UTC, clinssen commented
Thanks for the heroic review and comments! The remainder of the comments will be addressed in #1025 to keep the size and reviewability of this PR manageable.

2024-04-19 15:39 UTC, merged