Split process function into sub-routines
nest/nestml pull request #916
Opened 2023-06-14 14:31 UTC by med-ayssar

2023-06-21 22:35 UTC, clinssen approved these changes

2023-06-22 09:52 UTC, pnbabu requested changes

2023-06-22 09:52 UTC, pnbabu commented on pynestml/frontend/pynestml_frontend.py
> +   Handle the parsing, validation and transformation of the NESTML files
```suggestion
   Handle the parsing and validation of the NESTML files
```

2023-06-22 09:52 UTC, pnbabu commented on pynestml/frontend/pynestml_frontend.py
> +def transform_models(transformers, models):
Could you add docs to these functions?

2023-08-17 10:06 UTC, merged

2023-08-17 10:06 UTC, clinssen commented
Thanks!