Compartment Mechanism-Vectorization [WIP]
nest/nestml pull request #989
Opened 2023-11-16 13:35 UTC by LeanderEwert

Vectorizing the step-function calculations of all instances of a given mechanism-type in all compartments within a neuron.
Work in progress.

2024-01-29 10:38 UTC, WillemWybo commented
Fixes #1001

2024-07-11 10:43 UTC, clinssen requested changes

2024-07-11 10:43 UTC, clinssen commented on pynestml/codegeneration/resources_nest/point_neuron/directives_cpp/VectorizedFunctionDeclaration.jinja2
unused, please remove

2024-07-11 10:43 UTC, clinssen commented on tests/nest_compartmental_tests/resources/continuous_test.nestml
> +        spikes_AMPA <- spike
newline at end of file

2024-07-11 10:43 UTC, clinssen commented on tests/nest_compartmental_tests/resources/continuous_test.nestml
> +model continuous_test_model:
could you add a copyright header to the new .nestml files?

2024-07-11 10:43 UTC, clinssen commented on tests/nest_compartmental_tests/model_variable_initialization_test.py
> +class TestInitialization(unittest.TestCase):
please write a brief docstring explaining what is being tested

2024-07-11 10:43 UTC, clinssen commented on tests/nest_compartmental_tests/interaction_with_disabled_mechanism_test.py
> +if __name__ == "__main__":
these two lines can be removed, and unittest import can be removed, the class doesn't have to subclass unittest.TestCase any longer

2024-07-11 10:43 UTC, clinssen commented on tests/nest_compartmental_tests/interaction_with_disabled_mechanism_test.py
> +class TestCompartmentalMechDisabled(unittest.TestCase):
please write a brief docstring explaining what is being tested

2024-07-11 10:43 UTC, clinssen commented on tests/nest_compartmental_tests/interaction_with_disabled_mechanism_test.py
please rename the tests so the filenames start with ``test__`` for pytest discoverability

2024-07-11 10:43 UTC, clinssen commented on pynestml/codegeneration/resources_nest/point_neuron/directives/BufferGetter.jinja2
file can be removed

2024-07-11 10:43 UTC, clinssen commented on pynestml/codegeneration/resources_nest_compartmental/cm_neuron/@NEURON_NAME@.cpp.jinja2
> +/* REPLACED ONLY FOR TESTING OF CONTINUOUS INPUT
remove

2024-07-11 10:43 UTC, clinssen commented on pynestml/codegeneration/resources_nest_compartmental/cm_neuron/cm_neuroncurrents_@NEURON_NAME@.cpp.jinja2
> +// update {{ion_channel_name}} channel parameters
consider making this a docstring /* ... */

2024-07-11 10:43 UTC, clinssen commented on pynestml/codegeneration/resources_nest_compartmental/cm_neuron/cm_neuroncurrents_@NEURON_NAME@.cpp.jinja2
> +        if(getValue< double >( concentration_params, "{{key_zero_param}}" ) <= 1e-9){
could you make the 1e-9 a (static) const or #define somewhere?

2024-07-11 10:43 UTC, clinssen commented on pynestml/codegeneration/resources_nest_compartmental/cm_neuron/cm_neuroncurrents_@NEURON_NAME@.cpp.jinja2
> +        {%- with %}
```suggestion
```

2024-07-11 10:43 UTC, clinssen commented on pynestml/codegeneration/resources_nest_compartmental/cm_neuron/cm_neuroncurrents_@NEURON_NAME@.cpp.jinja2
> +
clean up whitespace

2024-07-11 10:43 UTC, clinssen commented on pynestml/codegeneration/resources_nest_compartmental/cm_neuron/cm_neuroncurrents_@NEURON_NAME@.h.jinja2
> +#include "ieee.h"
fastexp can go

2024-07-11 10:43 UTC, clinssen commented on pynestml/codegeneration/resources_nest_compartmental/cm_neuron/cm_neuroncurrents_@NEURON_NAME@.h.jinja2
> +{#-
can go

2024-07-11 10:43 UTC, clinssen commented on pynestml/codegeneration/resources_nest_compartmental/cm_neuron/cm_tree_@NEURON_NAME@.h.jinja2
> +#include <functional>
needed?

2024-07-11 10:43 UTC, clinssen commented on pynestml/codegeneration/resources_nest_compartmental/cm_neuron/setup/CMakeLists.txt.jinja2
> +        COMPILE_FLAGS "${NEST_CXXFLAGS} -DLTX_MODULE -march=native -ffast-math"
```suggestion
-ffast-math"
```
dangerous flag, mention in the documentation!

2024-07-11 10:43 UTC, clinssen commented on pynestml/grammars/dotnet-install.sh
can be deleted

2024-07-11 10:43 UTC, clinssen commented on pynestml/utils/con_in_info_enricher.py
> +    """Just created for consistency. No more than the base-class enriching needs to be done"""
what does this comment mean?

2024-07-11 10:43 UTC, clinssen commented on pynestml/utils/mechs_info_enricher.py
> +from pynestml.symbols.symbol import SymbolKind
alphabetical imports and sort by stdlib/custom imports please

2024-07-11 10:43 UTC, clinssen commented on setup.py
> +                               "codegeneration/resources_nest_compartmental/external/*",
can go now?

2024-07-11 10:43 UTC, clinssen commented on tests/nest_compartmental_tests/coap_error.log
remove

2024-07-11 10:43 UTC, clinssen commented on tests/nest_compartmental_tests/compartmental_model_test.py
> +                atol = 1.0
why larger tolerances?

2024-07-11 10:43 UTC, clinssen commented on tests/nest_compartmental_tests/compartmental_model_test.py
> +                atol = 1.0
same here

2024-07-11 10:43 UTC, clinssen commented on tests/nest_compartmental_tests/concmech_model_test.py
> +import unittest
```suggestion

```

2024-07-11 10:43 UTC, clinssen commented on tests/nest_compartmental_tests/concmech_model_test.py
> +class TestCompartmentalConcmech(unittest.TestCase):
```suggestion
class TestCompartmentalConcmech:
```

2024-07-11 10:43 UTC, clinssen commented on tests/nest_compartmental_tests/concmech_model_test.py
> +class TestCompartmentalConcmech(unittest.TestCase):
please add a little docstring explaining what is being tested

2024-07-11 10:43 UTC, clinssen commented on tests/nest_compartmental_tests/concmech_model_test.py
> +if __name__ == "__main__":
```suggestion

```

2024-07-11 10:43 UTC, clinssen commented on tests/nest_compartmental_tests/continuous_input_test.py
> +import unittest
```suggestion

```

2024-07-11 10:43 UTC, clinssen commented on tests/nest_compartmental_tests/continuous_input_test.py
> +class TestContinuousInput(unittest.TestCase):
docstring

2024-07-11 10:45 UTC, clinssen commented
Could you add some sentences on https://nestml.readthedocs.io/en/latest/running/running_nest_compartmental.html about new features/things that have changed? Mostly from user perspective but can also include some technical background (e.g. comment on performance).

2024-08-15 10:30 UTC, clinssen commented on tests/nest_compartmental_tests/test__concmech_model.py
> +            self.fail("the concentration (left) is not as expected (right). (" + str(res['c_Ca0'][data_array_index]) + "!=" + str(expected_conc) + ")")
self.fail only exists in unittest, use assert instead

2024-08-15 10:31 UTC, clinssen commented on doc/running/running_nest_compartmental.rst
> +We have put emphasis on delivering a good performance for neurons with high spacial complexity. We utilize vectorization
```suggestion
We have put emphasis on delivering a good performance for neurons with high spatial complexity. We utilize vectorization
```

2024-08-15 10:31 UTC, clinssen commented on doc/running/running_nest_compartmental.rst
> +therefor you should compile nest with the OpenMP flag enabled. This of course can only be utilized if your hardware
```suggestion
therefore you should compile nest with the OpenMP flag enabled. This of course can only be utilized if your hardware
```

2024-08-15 10:32 UTC, clinssen commented on doc/running/running_nest_compartmental.rst
> +your nestml model, meaning that you will get a better complexity/performance ratio the more instances of the same
```suggestion
your NESTML model, meaning that you will get a better complexity/performance ratio the more instances of the same
```

2024-08-15 10:33 UTC, clinssen commented on tests/nest_compartmental_tests/test__model_variable_initialization.py
> +            self.fail("the voltage (left) is not as expected (right). (" + str(
change to assert

2024-08-15 10:33 UTC, clinssen requested changes

2024-08-15 10:33 UTC, clinssen commented on tests/nest_compartmental_tests/test__model_variable_initialization.py
> +class TestInitialization(unittest.TestCase):
no need to inherit from UnitTest

2024-08-29 10:05 UTC, clinssen approved these changes

2024-08-29 10:05 UTC, merged